### ISSUE TITLE
Dispatch and home networks

### ISSUE THREAD

**Issue by sjmog** [Morhaus/dispatch-proxy#15]
Conjectural question: how would you go about running dispatch on a wireless repeater? For low-bandwidth areas that receive reasonable 3G signal, channel bonding multiple connections might be quite appealing.

**Comment by xy0** [comment]
Any further commentary about this?

**Comment by jsullivanlive** [comment]
My internet connections when traveling have improved a TON since 2013.  Now I can get a zte LTE card for 20$ and most places have 3g or better plans with reasonable data caps, so I don't know where I'd test this today.

**Comment by rlindsberg** [comment]
Issue closed.
