### ISSUE TITLE
How loadbalancin is acheived

### ISSUE THREAD

**Issue by manjurajv** [Morhaus/dispatch-proxy#22]
Hi Morhaus,

I am exploring dispatch-proxy. As I am new to coffee(java script), I am feeling bit difficult to understand how load balancing is achieved.

Assume I am uploading a youtube video(10 MB) via dispatch-proxy with wlan0, 3g/4g connections (wlan0@1 pdp0@1) running at equal speeds, how can dispatch proxy divide the upload equally among two interfaces.

Does socks proxy support ftp upload(tcp) balancing/dns(udp) query balancing

**Comment by FinlayDaG33k** [comment]
So basically it does not balance the packets themselves but rather connection-based.

**Comment by rlindsberg** [comment]
Like Morhaus said, In the future it will look at the total traffic of those connections instead of number of connections. Issue solved.
