### ISSUE TITLE
Setting up Raspberry Pi Hotspot with Dispathc-Proxy

### ISSUE THREAD

**Issue by mikesumbler** [Morhaus/dispatch-proxy#26]
Hi,

I want to use dispath to provide http / socks5 proxy for connection to the internet, combining 3G and Ethernet connections and then sharing over Wifi hotspot. I've spent quite sometime setting it up and am now at a point where I'm ready to merge the connections. 

All is fine (I'll probably need to put dispath in looping script as 3G ip isn't static), but how do then provide proxy to those over internet, i.e. how to I allow remote connection to local host. I've tried setting up Linux Firewall (iptables) to allow connection from wlan0 but to no avail. 

Any ideas.

Help much apprecicated. I can provide more details logs etc as required.

Cheers
Mike

**Comment by rlindsberg** [comment]
Please refer to the documentation at https://github.com/Morhaus/dispatch-proxy/tree/master/docs.
