### ISSUE TITLE
request 127.0.0.1:54000   error serverConnection

### ISSUE THREAD

**Issue by graphical-iain** [Morhaus/dispatch-proxy#36]
Hello!
So I started up the dispatch service to two ips, and I'm getting a bunch of errors.
I ran it with the --debug option and this is what I got.

```
SOCKS server started on localhost:1080
Dispatching to addresses 192.168.116.228@1, 192.168.1.134@1
   request [efa0a9] 127.0.0.1:54000
  dispatch [efa0a9] 192.168.116.228
     error [efa0a9] serverConnection
           Error: connect ECONNREFUSED
               at errnoException (net.js:904:11)
               at Object.afterConnect [as oncomplete] (net.js:895:19)
       end [efa0a9] clientConnection
   request [acac53] 127.0.0.1:54000
  dispatch [acac53] 192.168.1.134
     error [acac53] serverConnection
           Error: connect ECONNREFUSED
               at errnoException (net.js:904:11)
               at Object.afterConnect [as oncomplete] (net.js:895:19)
       end [acac53] clientConnection
```

It would repeat this every few seconds for the length of time that i had the service running. As you can see, it's the same error happening on both IPs that I'm bridging. I can still connect to the network and websites while the service is running, so I'm not sure if it's a dire issue, but it's just alarming to get quite so many errors.

I'm running OSX 10.10.1 (Yosemite)
NPM version 1.4.28

Thanks in advance!

**Comment by Morhaus** [comment]
You probably have a service on your computer that tries to connect to a local server (127.0.0.1:54000) that isn't running, hence the error. It most likely has nothing to do with the proxy, but is still reported as an error.

However, if you note that you can't access a particular address or hostname through the proxy, you can add a bypass rule in System Preferences. "Bypass proxy settings for these Hosts & Domains" is right under where you enter the proxy address and port.
