### ISSUE TITLE
dispatch hangs when client supports gssapi

### ISSUE THREAD

**Issue by akashrawal** [Morhaus/dispatch-proxy#38]
dispatch-proxy works with firefox but not with curl. 

Further examination revealed that when newly connected client sends 3 bytes {0x05, 0x01, 0x00} (as in case of firefox) the proxy sends back {0x05, 0x00} and works properly. But when client sends 4 bytes {0x05, 0x02, 0x00, 0x01} (in case of curl) the server hangs.

**Comment by Morhaus** [comment]
Should be fixed in 0.1.3, can you update and try again?

**Comment by akashrawal** [comment]
Thanks, it now works after updating.
