### ISSUE TITLE
Configure dispatch proxy for proxy internet connections

### ISSUE THREAD

**Issue by kkb350** [Morhaus/dispatch-proxy#56]
I did all the steps as mentioned in the dispatch proxy documentation.But one thing is that my internet connection goes through a proxy 172.16.0.5:3128 so I donot know how to configure the commands behind the proxy.Please tell solution..

**Comment by rlindsberg** [comment]
Please refer to the documentation at https://github.com/Morhaus/dispatch-proxy/tree/master/docs.
