### ISSUE TITLE
can not install!

### ISSUE THREAD

**Issue by heforfree** [Morhaus/dispatch-proxy#58]
hi i can not install it
https://gist.github.com/heforfree/e8c3d12cf217f11b5690#file-dispatch

**Comment by Morhaus** [comment]
This issue is not related to dispatch-proxy itself. Looks like you have network issues that prevent you from installing a module with npm.

```
39 error network This is most likely not a problem with npm itself
39 error network and is related to network connectivity.
39 error network In most cases you are behind a proxy or have bad network settings.
39 error network
39 error network If you are behind a proxy, please make sure that the
39 error network 'proxy' config is set properly.  See: 'npm help config'
```

**Comment by heforfree** [comment]
i don't use any proxy and i can connect net.
my connection is ppoe and in modem is this.
but i Guess it because UDP.i think isp blocked somehow that.

**Comment by heforfree** [comment]
is there anyway install it offline?

**Comment by Morhaus** [comment]
I recommend you look on Google for people with similar issues. NPM is mandatory in order to install dispatch-proxy.

**Comment by heforfree** [comment]
ok thank you very much.helped me
used this command
npm config set registry http://registry.npmjs.org/     set to http
npm config set proxy http://find-p-r-o-x-y:port        set p-r-o-x-y
npm install -g dispatch-proxy                                   install dispatch
dispatch -V                                                             check installed 0.1.4
npm config rm proxy                                             remove p-r-o-x-y
