### ISSUE TITLE
how to dispatch 2 wifi connections at same time

### ISSUE THREAD

**Issue by AiBuddy** [Morhaus/dispatch-proxy#59]
How can i connect two wifi connects at the same time ????

**Comment by huanga** [comment]
You'll need two wireless dongles, and connect each one of them to a different WiFi access point. Once done, it is business per usual, `dispatch start` and you're off the races.

**Comment by Collins-a** [comment]
Also if supported by your WiFi card, you may create two virtual interfaces with it, assign to them different mac address then connect to two different networks

**Comment by Saxin** [comment]
Hi is it possible to connect say x3 wifi to same network / router - I want speed aggregation ?

**Comment by huanga** [comment]
@Saxin Similar to my and @collin5 's comment from 2016, you will need 3 wireless dongles or a wireless card that supports virtual interfaces. I do not know if you will get better performance, or just generate a lot of wireless noise, though.

**Comment by rlindsberg** [comment]
Please refer to the documentation at https://github.com/Morhaus/dispatch-proxy/tree/master/docs.
