### ISSUE TITLE
How to use with a "proxy" network

### ISSUE THREAD

**Issue by Collins-a** [Morhaus/dispatch-proxy#60]
My ISP requires me to connect using proxy, How can I make dispatch use proxy settings. I'm using linux, so any linux solutions would be greatly appreciated

**Comment by Morhaus** [comment]
Try using a proxifier tool like [Profixier](http://www.proxifier.com/) to customize your proxy settings. You might be able to make a connection run through both a local proxy and a distant proxy.

**Comment by Collins-a** [comment]
Proxifier failed to work on  Arch using wine, But I was able to get around it using <a href="https://www.archlinux.org/packages/community/x86_64/proxychains-ng/">proxychains</a>. Thanks alot.
