### ISSUE TITLE
Error: connect EADDRNOTAVAIL

### ISSUE THREAD

**Issue by Meomeoowww** [Morhaus/dispatch-proxy#61]
Hello !  My English skills are poor so excuse me in advance ! I'm trying to make dispatch run on Win 10 PC. I wanted to merge an ethernet and wifi cards but i get some errors. I use SOCK and i get this error:
C:\Users\Eddie>dispatch start --debug
SOCKS server started on localhost:1080
Dispatching to addresses 192.168.21.100@1, 192.168.21.103@1
   request [22e049] 216.58.209.163:443
  dispatch [22e049] 192.168.21.100
   connect [22e049] 216.58.209.163:443
   request [0e7d5d] 172.217.19.206:443
  dispatch [0e7d5d] 192.168.21.103
   connect [0e7d5d] 172.217.19.206:443
   request [0658fe] 127.245.107.154:443
  dispatch [0658fe] 192.168.21.100
   request [961fda] 127.245.107.154:443
  dispatch [961fda] 192.168.21.103
   request [d1e653] 127.245.107.154:443
  dispatch [d1e653] 192.168.21.100
   request [797172] 127.245.107.154:443
  dispatch [797172] 192.168.21.103
   request [93070c] 127.245.107.154:443
  dispatch [93070c] 192.168.21.100
   request [8e5257] 127.245.107.154:443
  dispatch [8e5257] 192.168.21.103
   request [49edaf] 169.55.74.42:443
  dispatch [49edaf] 192.168.21.100
   request [f8d683] 169.55.74.42:443
  dispatch [f8d683] 192.168.21.103
     error [0658fe] serverConnection
           Error: connect EADDRNOTAVAIL 127.245.107.154:443
               at Object.exports._errnoException (util.js:1007:11)
               at exports._exceptionWithHostPort (util.js:1030:20)
               at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
     error [961fda] serverConnection
           Error: connect EADDRNOTAVAIL 127.245.107.154:443
               at Object.exports._errnoException (util.js:1007:11)
               at exports._exceptionWithHostPort (util.js:1030:20)
               at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
     error [d1e653] serverConnection
           Error: connect EADDRNOTAVAIL 127.245.107.154:443
               at Object.exports._errnoException (util.js:1007:11)
               at exports._exceptionWithHostPort (util.js:1030:20)
               at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
     error [797172] serverConnection
           Error: connect EADDRNOTAVAIL 127.245.107.154:443
               at Object.exports._errnoException (util.js:1007:11)
               at exports._exceptionWithHostPort (util.js:1030:20)
               at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
     error [93070c] serverConnection
           Error: connect EADDRNOTAVAIL 127.245.107.154:443
               at Object.exports._errnoException (util.js:1007:11)
               at exports._exceptionWithHostPort (util.js:1030:20)
               at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
     error [8e5257] serverConnection
           Error: connect EADDRNOTAVAIL 127.245.107.154:443
               at Object.exports._errnoException (util.js:1007:11)
               at exports._exceptionWithHostPort (util.js:1030:20)
               at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
       end [0658fe] clientConnection
       end [961fda] clientConnection
       end [d1e653] clientConnection
       end [797172] clientConnection
       end [93070c] clientConnection
       end [8e5257] clientConnection
   request [6df145] 169.55.74.42:443
  dispatch [6df145] 192.168.21.100
   request [fbaea7] 169.55.74.42:443
  dispatch [fbaea7] 192.168.21.103
   request [fd65bd] 172.217.19.206:443
  dispatch [fd65bd] 192.168.21.100
   request [782d73] 172.217.19.206:443
  dispatch [782d73] 192.168.21.103
   request [c516f9] 172.217.19.206:443
  dispatch [c516f9] 192.168.21.100
   request [4ac159] 172.217.19.206:443
  dispatch [4ac159] 192.168.21.103
   request [f5f74b] 179.60.192.51:443
  dispatch [f5f74b] 192.168.21.100
   request [7cf878] 179.60.192.51:443
  dispatch [7cf878] 192.168.21.103
   connect [f8d683] 169.55.74.42:443
   connect [49edaf] 169.55.74.42:443
   connect [6df145] 169.55.74.42:443
   connect [fd65bd] 172.217.19.206:443
   connect [782d73] 172.217.19.206:443
   connect [4ac159] 172.217.19.206:443
   connect [c516f9] 172.217.19.206:443
   connect [fbaea7] 169.55.74.42:443
   request [50e893] 179.60.192.51:443
  dispatch [50e893] 192.168.21.100
   request [9dbf8b] 74.125.136.95:443
  dispatch [9dbf8b] 192.168.21.103
   request [237db5] 169.55.74.50:443
  dispatch [237db5] 192.168.21.100
   connect [f5f74b] 179.60.192.51:443
   connect [7cf878] 179.60.192.51:443
   connect [50e893] 179.60.192.51:443
   connect [9dbf8b] 74.125.136.95:443
   request [7be314] 172.217.19.206:443
  dispatch [7be314] 192.168.21.103
   connect [237db5] 169.55.74.50:443
   connect [7be314] 172.217.19.206:443
       end [fbaea7] clientConnection
   request [fec5c4] 169.55.74.36:443
  dispatch [fec5c4] 192.168.21.100
   connect [fec5c4] 169.55.74.36:443
   request [fe607d] 216.58.209.195:443
  dispatch [fe607d] 192.168.21.103
   request [34faa9] 216.58.209.195:443
  dispatch [34faa9] 192.168.21.100
   request [fc3b62] 216.58.209.195:443
  dispatch [fc3b62] 192.168.21.103
   request [79c87f] 216.58.209.195:443
  dispatch [79c87f] 192.168.21.100
   request [2c41fd] 216.58.209.195:443
  dispatch [2c41fd] 192.168.21.103

Can you explain it to me why ? Thanks

**Comment by Morhaus** [comment]
Something on your computer is trying to access 127.245.107.154:443, but the address does not exist or is not available from whichever interface the connection was dispatched to.

Are you noticing lost connections outside of the command prompt as well? Most of the errors reported by the proxy aren't important and can be ignored.

**Comment by Meomeoowww** [comment]
Oh ok I see, so i can just mute all erros reported, right ?

**Comment by Morhaus** [comment]
Yup.

**Comment by Meomeoowww** [comment]
Many Thanks. Thread closed
