### ISSUE TITLE
restart on error

### ISSUE THREAD

**Issue by iGhoneim** [Morhaus/dispatch-proxy#65]
**Scenario**:
I've started a SOCKS 5 proxy resulted from running dispatch-proxy by:
`$ dispatch start --debug
`
Sometimes, an error occurs and written on terminal like:

```
error [f6d77b] serverConnection
           Error: read ECONNRESET
               at exports._errnoException (util.js:1008:11)
               at TCP.onread (net.js:563:26)
```

**How** to restart proxy on error?

Something like:

```
while(true){
  cmd.run
  while(!cmd.err){}
}
```

**Comment by rlindsberg** [comment]
For now you have to restart it manually.
