### ISSUE TITLE
error [7f94f9] clientRequest

### ISSUE THREAD

**Issue by kevinmustaqim** [Morhaus/dispatch-proxy#67]
This program is not working properly, I think you have miss while do parsing, please correct your code again:

`wget use_proxy=yes -e http_proxy=localhost:8080 http://speedtest.wdc01.softlayer.com/downloads/test10.zip -O /dev/null`
--2016-09-05 12:15:41--  http://use_proxy=yes/
Resolving localhost (localhost)... ::1, 127.0.0.1
Connecting to localhost (localhost)|::1|:8080... failed: Connection refused.
Connecting to localhost (localhost)|127.0.0.1|:8080... connected.
Proxy request sent, awaiting response... 502 Bad Gateway
2016-09-05 12:15:41 ERROR 502: Bad Gateway.

--2016-09-05 12:15:41--  http://speedtest.wdc01.softlayer.com/downloads/test10.zip
Reusing existing connection to localhost:8080.
Proxy request sent, awaiting response... 

^C

And here are debug results i got

  request [7f94f9] http://use_proxy=yes/
  dispatch [7f94f9] 192.168.1.106
       end [7f94f9] clientRequest
     error [7f94f9] clientRequest
           Error: getaddrinfo ENOTFOUND use_proxy use_proxy:80
               at errnoException (dns.js:27:10)
               at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:78:26)
   request [457fd4] http://speedtest.wdc01.softlayer.com/downloads/test10.zip
  dispatch [457fd4] 10.192.244.194
       end [457fd4] clientRequest
     error [b14a19] clientRequest
           Error: connect ETIMEDOUT 208.43.102.250:80
               at Object.exports._errnoException (util.js:907:11)
               at exports._exceptionWithHostPort (util.js:930:20)
               at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1077:14)

**Comment by Morhaus** [comment]
Your `wget` command is wrong.

You should do

```
wget -e use_proxy=yes -e http_proxy=localhost:8080 http://speedtest.wdc01.softlayer.com/downloads/test10.zip -O /dev/null
```

**Comment by kevinmustaqim** [comment]
hah? lol 
You should be careful before writing comments, my code is not different with yours
