### ISSUE TITLE
How to make Dispatch-Proxy work at the System level

### ISSUE THREAD

**Issue by Raybo58** [Morhaus/dispatch-proxy#69]
This only works for Windows 8 through 10 and only if you're setting up a Socks proxy, rather than an HTTP proxy.  After many hours of experimentation, I finally figured out how to configure Dispatch for use on the system level. You can't use the Network & Internet settings page from Windows 8 through 10. Whatever you enter there will end up screwing up the configuration. You have to go to the Contol Panel  and open `Internet Options` and go to the `Connections` tab. From there you want to go to the `Proxy Server` section and check `Use a proxy server for your LAN` and `Bypass proxy server for local addresses`. Then you want to click the `Advanced` button and on the page that opens you want to make sure every field is empty except the `Socks:`  fields. There you want to enter `socks` for the `Proxy address to use` and `1080` for the `Port`. Also, make sure that the `Use the same proxy server for all protocols` box is unchecked. After using this method, every app on my system uses Dispatch-Proxy.

**Comment by rlindsberg** [comment]
No issue. Closing.
